### ISSUE TITLE
How to set some data in session in functional test?

### ISSUE THREAD

**Issue by shubaivan** [liip/LiipFunctionalTestBundle#414] opened 2018-04-23 18:23 UTC
I use `"liip/functional-test-bundle": "~1.8",` and `"symfony/symfony": "~3.4",` and for my functional test I want set some data in session,but after set data in action, with the same key, I had null. Mytest class extends from `extends WebTestCase`

this is how I set data in test method  

        $session = $this->container->get('session');
        $session->set('test', 2);

        $this->getClient()->request(
            Request::METHOD_GET,
            $routing
        );

config_test.yml

    framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: "MOCKSESSID"
    profiler:
        collect: false

and in action 

    public function getEntityAction()
    {
        $test = $this->get('session')->get('test');
    
variable `$test` equal null
How to set some data in session in functional test ?

**Comment by alexislefebvre** [comment] 2018-04-23 20:00
Someone had the same question in #383.

I think that the test should follow the same path than the one used by visitors. So you'll test that the data is wrote in session and readen later.

**Comment by Jean85** [comment] 2018-04-24 07:35
I think the main mistake here is forgetting that `$this->container` is NOT the same as `$client->getContainer()`: the Client spuns a completely separated, new container, and depending on how you use the session, you may not find the same stuff in both of them.

**Comment by alexislefebvre** [comment] 2018-05-03 11:40
@Jean85 Do you remember if `$this->getContainer()` returns the container of the *real* application?

**Comment by alexislefebvre** [comment] 2018-05-03 11:43
Question on SO: https://stackoverflow.com/questions/48915859/symfony-3-mock-service-in-functional-tests-phpunit-and-liip

**Comment by Jean85** [comment] 2018-05-03 12:58
@alexislefebvre yes you get a real container, but it's not the same instance as `$client->getContainer()`; it's separated do avoid collisions or issues while testing through the client.

**Comment by alexislefebvre** [comment] 2018-06-11 22:40
@shubaivan Did you try to use the client's container?

It may work with something like this:

```php
$client = $this->makeClient();
$client->getContainer()->set('test', 2);
$crawler = $client->request('GET', '/contact');
```

**Comment by alexislefebvre** [comment] 2018-06-21 15:34
I'm closing this issue for now. Feel free to reopen it if the problem is not solved.

**Closed by alexislefebvre** 2018-06-21 15:34 UTC
Labels: support
