### ISSUE TITLE
make it more obvious that the bundle provide a conveniency method to create authentified client

### ISSUE THREAD

**Issue by allan-simon** [liip/LiipFunctionalTestBundle#140] opened 2015-02-20 06:44 UTC
the WebTestCase class provide 2 public method ,  `makeClient` and `loginAs` which are not advertized though they prove quite useful as they cover the very common case of doing functionnal tests on pages that require authentication, it would be great if the documentation was mentioning them

**Comment by lsmith77** [comment] 2015-02-23 10:47
can you submit a PR to improve the README?

**Comment by allan-simon** [comment] 2015-02-23 13:13
done, I haven't used loginAs (as I'm not sure how it should be used, hency my MR =) ) so I haven't /can't  add documentation for it

**Comment by lsmith77** [comment] 2015-02-23 13:21
ok thx. leaving it open until someone manages to document the other mehod

**Comment by johnkary** [comment] 2015-02-24 00:00
@allan-simon Thanks for the PR! I used it today for the first time and saved me some time diving into the code :)

**Comment by lsmith77** [comment] 2016-01-07 06:55
duplicate of https://github.com/liip/LiipFunctionalTestBundle/issues/88

**Closed by lsmith77** 2016-01-07 06:55 UTC
