### ISSUE TITLE
The service definition "validator" does not exist.

### ISSUE THREAD

**Issue by andriylekh** [liip/LiipFunctionalTestBundle#185] opened 2015-11-27 16:04 UTC
After 58bb1d2c6717d08ddd2cc3b90ba3567c55942aa9 commit have a problem with loading validator.

**Comment by lsmith77** [comment] 2015-12-03 14:06
I doubt that this could be caused by that commit. I suspect its more related to potentially having updated other dependencies.

**Comment by sc0rp10** [comment] 2015-12-04 08:00
@lsmith77 how do I test bundle without internal unit-tests? Maybe you're have any ideas? I can fix it issue, but i don't know how can I check my work.

**Comment by lsmith77** [comment] 2015-12-04 08:52
yeah. essentially tests need to be created from scratch :-/

**Comment by sc0rp10** [comment] 2015-12-04 09:02
@andriylekh any details? symfony version, stacktrace etc

**Comment by lsmith77** [comment] 2015-12-05 13:09
I created https://github.com/liip/LiipFunctionalTestBundle/pull/189/files

**Comment by tarioch** [comment] 2015-12-17 22:03
I'm getting exactly the same issue:
https://travis-ci.org/tarioch/eveapi-fetcher-bundle

**Comment by lsmith77** [comment] 2016-01-07 06:22
should be fixed now

**Closed by lsmith77** 2016-01-07 06:22 UTC
