### ISSUE TITLE
annotation "@group" in method was never imported

### ISSUE THREAD

**Issue by sirroman** [liip/LiipFunctionalTestBundle#495] opened 2019-03-06 12:32 UTC
liip does not know @group annotation after update to 2.0.0-alpha14
```
# composer update liip/functional-test-bundle
....
Updating liip/functional-test-bundle (2.0.0-alpha12 => 2.0.0-alpha14):
...
```
### Preconditions

PHP 7.2.12
PHPUnit 7.5.6

### Steps to reproduce

1. install fresh symfony 
```
symfony new --full my_project
```
2. write simple test
```php
<?php
namespace Tests\Controller;
use Liip\FunctionalTestBundle\Test\WebTestCase;
class ApiControllerTest extends WebTestCase
{
   /**
     * @group d3
     */
    public function testGetMediaLikes2()
    {
        $this->loadFixtures([]);
        $this->assertTrue(true);
    }
}
```
3. run test
```
bin/phpunit --group=d3
```
you just clone repostitory https://github.com/sirroman/liip2.0.0-alpha14-error

### Actual result

1. [Screenshot, logs]

```
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@group" in method Tests\Controller\ApiControllerTest::testTest2() was never imported. Did you maybe forget to add a "use" statement for this annotation?

vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:727
vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:663
vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:354
vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php:286
vendor/liip/functional-test-bundle/src/Services/DatabaseToolCollection.php:71
vendor/liip/functional-test-bundle/src/Services/DatabaseToolCollection.php:61
vendor/liip/functional-test-bundle/src/Test/WebTestCase.php:255
tests/unit/Controller/ApiControllerTest.php:43
```

**Comment by temp** [comment] 2019-03-07 20:35
Same here, with @dataProvider.

**Comment by alexislefebvre** [comment] 2019-03-08 22:42
You can try this:

1. Create file `tests/bootstrap.php` with the following content:

```
<?php

declare(strict_types=1);

use Doctrine\Common\Annotations\AnnotationRegistry;

$loader = require __DIR__.'/../vendor/autoload.php';

AnnotationRegistry::registerLoader([$loader, 'loadClass']);

return $loader;
```

2. Configure path to this file in `phpunit.xml.dist`:

```
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/6.5/phpunit.xsd"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
>
```

If this works for you, we could add it to the documentation.

**Comment by alexislefebvre** [comment] 2019-03-08 22:46
Or you can try to use `@IgnoreAnnotation`: https://github.com/liip/LiipFunctionalTestBundle/blob/1845a0f21a81ecf589fef0543e0189187e049f6d/README.md#caveats

**Comment by jrjohnson** [comment] 2019-03-10 01:12
The issue is that this library is now parsing annotations in tests due to #484. The `doctrine/annotations` library throws an error whenever it finds an annotation that it doesn't understand. I had never seen this error before because no library had ever attempted to parse test files.
 I've opened https://github.com/doctrine/annotations/pull/254 over there to add the PHPUnit annotations to the set of default ignored annotations. Before that is released you will either need to take @alexislefebvre's advice and skip individual annotations or inform `doctrine/annotations` of your app's annotations in some kind of bootstrap file.  I temporarily added the ones I needed (covers and group) to `config/bootstrap.php` as
 
```
use Doctrine\Common\Annotations\AnnotationReader;

AnnotationReader::addGlobalIgnoredName('covers');
AnnotationReader::addGlobalIgnoredName('group');
```

**Comment by sirroman** [comment] 2019-03-11 12:24
> You can try this:
> 
> 1. Create file `tests/bootstrap.php` with the following content:
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> use Doctrine\Common\Annotations\AnnotationRegistry;
> 
> $loader = require __DIR__.'/../vendor/autoload.php';
> 
> AnnotationRegistry::registerLoader([$loader, 'loadClass']);
> 
> return $loader;
> ```
> 1. Configure path to this file in `phpunit.xml.dist`:
> 
> ```
> <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>          xsi:noNamespaceSchemaLocation="http://schema.phpunit.de/6.5/phpunit.xsd"
>          backupGlobals="false"
>          colors="true"
>          bootstrap="tests/bootstrap.php"
> >
> ```
> If this works for you, we could add it to the documentation.

does not work

**Comment by alexislefebvre** [comment] 2019-03-16 19:07
Adding `@IgnoreAnnotation("requires")` fixed the issue for me: https://github.com/alexislefebvre/AsyncTweetsBundle/pull/68/files

**Comment by alexislefebvre** [comment] 2019-03-16 19:28
Please see #497

**Comment by alexislefebvre** [comment] 2019-03-16 19:28
@sirroman Please see #497

**Comment by alexislefebvre** [comment] 2019-04-24 21:11
I'm closing this issue, please reopen it if #497 doesn't solve the issue.

**Closed by alexislefebvre** 2019-04-24 21:11 UTC

**Comment by pauliuslukosiunas** [comment] 2019-06-19 10:12
> The issue is that this library is now parsing annotations in tests due to #484. The `doctrine/annotations` library throws an error whenever it finds an annotation that it doesn't understand. I had never seen this error before because no library had ever attempted to parse test files.
> I've opened [doctrine/annotations#254](https://github.com/doctrine/annotations/pull/254) over there to add the PHPUnit annotations to the set of default ignored annotations. Before that is released you will either need to take @alexislefebvre's advice and skip individual annotations or inform `doctrine/annotations` of your app's annotations in some kind of bootstrap file. I temporarily added the ones I needed (covers and group) to `config/bootstrap.php` as
> 
> ```
> use Doctrine\Common\Annotations\AnnotationReader;
> 
> AnnotationReader::addGlobalIgnoredName('covers');
> AnnotationReader::addGlobalIgnoredName('group');
> ```

this one solved my problem :)
