### ISSUE TITLE
WebTest case is not working with nelmio alice 3.0

### ISSUE THREAD

**Issue by Pherserk** [liip/LiipFunctionalTestBundle#297] opened 2016-12-22 15:54 UTC
A class "Fixtures" is need by the method loadFixtures, Isuppose it has become FixtureSet in nelmio\alice 3.0.

I get this error:
"BadMethodCallException: nelmio/alice should be installed to use this method."

Any workaround?

Many thanks

**Comment by alexislefebvre** [comment] 2016-12-27 15:01
Alice's maintainer added the issue #268 as a notification but no action has been taken for Nelmio Alice 3.0 yet.

**Comment by theofidry** [comment] 2017-01-20 14:46
Indeed there is several BC breaks between nelmio/alice 2.x and 3.x. There is little BC breaks for the average user regarding the syntax and features, but it's a complete overhaul of alice API and its internal. For now there is not easy way to upgrade from alice 2.x API to 3.x, it might be something that will be done if there's a strong interest and demand. As a result I would:

- Either stick to alice 2.x if you are using LiipBundle
- Don't use LiipBundle in favour of alice 3.x
- Help LiipBundle to upgrade to alice 3.x

Note that alice 3.x is still in beta for a few reason:

- There is some internal stuff that I want to change still. It should be very scoped but I'm uneasy to tag a stable release before that stuff is done
- I'm curious to see how the upgrade is done in a few integrations such as LiipBundle as I want to make sure alice 3.x is more easily extendable than 2.x

**Comment by zhil** [comment] 2017-05-14 21:17
added workaround for nelmio/alice v3 in PR https://github.com/liip/LiipFunctionalTestBundle/pull/320

**Comment by Soullivaneuh** [comment] 2017-10-31 12:49
This issue should be closed as it's a duplicate of #268.

**Comment by alexislefebvre** [comment] 2018-01-17 13:28
Fixed in #379.

**Closed by alexislefebvre** 2018-01-17 13:28 UTC
Labels: verified
