### ISSUE TITLE
Since upgrading to Symfony 2.7 I am getting a ValidatorInterface error

### ISSUE THREAD

**Issue by ccapndave** [liip/LiipFunctionalTestBundle#212] opened 2016-01-12 15:21 UTC
Since I upgraded my site to use Symfony 2.7 I get the following error which I can only fix by commenting out the `LiipFunctionalTestBundle` in `AppKernel`.

```
ContextErrorException in MetaValidator.php line 32:
Catchable Fatal Error: Argument 1 passed to Lunetics\LocaleBundle\Validator\MetaValidator::__construct() must implement interface Symfony\Component\Validator\ValidatorInterface, instance of Liip\FunctionalTestBundle\Validator\DataCollectingValidator given, called in /run/shm/3905ff5264cc3ea9677ebd220507cc17/cache/dev/appDevDebugProjectContainer.php on line 5950 and defined
in MetaValidator.php line 32
at ErrorHandler->handleError('4096', 'Argument 1 passed to Lunetics\LocaleBundle\Validator\MetaValidator::__construct() must implement interface Symfony\Component\Validator\ValidatorInterface, instance of Liip\FunctionalTestBundle\Validator\DataCollectingValidator given, called in /run/shm/3905ff5264cc3ea9677ebd220507cc17/cache/dev/appDevDebugProjectContainer.php on line 5950 and defined', '/vagrant/vendor/lunetics/locale-bundle/Lunetics/LocaleBundle/Validator/MetaValidator.php', '32', array()) in MetaValidator.php line 32
at MetaValidator->__construct(object(DataCollectingValidator)) in appDevDebugProjectContainer.php line 5950
at appDevDebugProjectContainer->getLuneticsLocale_Validator_MetaService() in bootstrap.php.cache line 2140
at Container->get('lunetics_locale.validator.meta') in appDevDebugProjectContainer.php line 5840
at appDevDebugProjectContainer->getLuneticsLocale_RouterGuesserService() in bootstrap.php.cache line 2140
at Container->get('lunetics_locale.router_guesser') in appDevDebugProjectContainer.php line 5739
at appDevDebugProjectContainer->getLuneticsLocale_GuesserManagerService() in bootstrap.php.cache line 2140
at Container->get('lunetics_locale.guesser_manager') in appDevDebugProjectContainer.php line 5782
at appDevDebugProjectContainer->getLuneticsLocale_LocaleListenerService() in bootstrap.php.cache line 2140
at Container->get('lunetics_locale.locale_listener') in classes.php line 1929
at ContainerAwareEventDispatcher->lazyLoad('kernel.request') in classes.php line 1897
at ContainerAwareEventDispatcher->getListeners('kernel.request') in TraceableEventDispatcher.php line 227
at TraceableEventDispatcher->preProcess('kernel.request') in TraceableEventDispatcher.php line 119
at TraceableEventDispatcher->dispatch('kernel.request', object(GetResponseEvent)) in bootstrap.php.cache line 3083
at HttpKernel->handleRaw(object(Request), '2') in bootstrap.php.cache line 3056
at HttpKernel->handle(object(Request), '2', false) in bootstrap.php.cache line 3207
at ContainerAwareHttpKernel->handle(object(Request), '2', false) in ExceptionListener.php line 50
at ExceptionListener->onKernelException(object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher))
at call_user_func(array(object(ExceptionListener), 'onKernelException'), object(GetResponseForExceptionEvent), 'kernel.exception', object(TraceableEventDispatcher)) in WrappedListener.php line 61
at WrappedListener->__invoke(object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher))
at call_user_func(object(WrappedListener), object(GetResponseForExceptionEvent), 'kernel.exception', object(ContainerAwareEventDispatcher)) in classes.php line 1824
at EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.exception', object(GetResponseForExceptionEvent)) in classes.php line 1757
at EventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in classes.php line 1918
at ContainerAwareEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in TraceableEventDispatcher.php line 124
at TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent)) in bootstrap.php.cache line 3126
at HttpKernel->handleException(object(ContextErrorException), object(Request), '1') in bootstrap.php.cache line 3062
at HttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 3207
at ContainerAwareHttpKernel->handle(object(Request), '1', true) in bootstrap.php.cache line 2429
at Kernel->handle(object(Request)) in app_dev.php line 28
```

**Comment by alexislefebvre** [comment] 2016-01-12 16:58
Duplicate of #178?

**Comment by alexislefebvre** [comment] 2016-01-12 17:00
What version of this bundle is defined in your `composer.json` file?

**Comment by ccapndave** [comment] 2016-01-13 11:09
`"liip/functional-test-bundle": "dev-master"`

**Comment by lsmith77** [comment] 2016-01-13 20:56
as stated above .. the issue is with the LuneticsLocaleBundle not with this Bundle.

**Closed** 2016-01-13 20:55 UTC

**Comment by vladimirgolub** [comment] 2016-11-21 11:59
Conflict with LuneticsTimezoneBundle

**Comment by lsmith77** [comment] 2016-11-23 11:12
https://github.com/liip/LiipFunctionalTestBundle/issues/212#issuecomment-171407763
