### ISSUE TITLE
[3.x] Wrong version of the package loaded with Composer

### ISSUE THREAD

**Issue by gnutix** [liip/LiipFunctionalTestBundle#528] opened 2019-06-13 13:30 UTC
It's a very strange thing I'm experiencing : I've included `"liip/functional-test-bundle": "~3.0@RC",` in my `require-dev` section of `composer.json`, and yet when I run `composer update liip/functional-test-bundle`, I get the version `3.0.0-RC1` instead of, in my opinion, `3.0.0-RC2`. The same with `~3.0@alpha`, which gets me `3.0.0-alpha1` instead of `3.0.0-alpha2`.

Any idea how/why this happens ? Should I open the issue on Composer's side ? (I've never had this with another library)

**Comment by alexislefebvre** [comment] 2019-06-13 16:34
What version of Symfony do you use? `4.3.0`?

In this case, it's due to the conflict added in last releases: https://github.com/liip/LiipFunctionalTestBundle/commit/c2201eaca775b70369385d35b9aa082b37c8d087#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R34

Please try again when Symfony `4.3.1` is installed.

**Comment by alexislefebvre** [comment] 2019-06-30 17:13
@gnutix Did you found a solution?

**Comment by alexislefebvre** [comment] 2019-07-08 21:11
I'm closing this issue, you can now use the sable release 3.0. Feel free to reopen this issue if the problem is still present.

**Closed by alexislefebvre** 2019-07-08 21:11 UTC
Labels: support
