### ISSUE TITLE
Details on how to use the loginAs functionality 

### ISSUE THREAD

**Issue by phillipsnick** [liip/LiipFunctionalTestBundle#161] opened 2015-07-06 14:29 UTC
I'm currently trying to test some secure sections of my application and came across the `loginAs` method on the WebTestCase class.

The documentation isn't very clear on how to actually utilise this feature and from what I can tell it doesn't actually work? But then I might be using it incorrectly. 

Also from looking at the below config example, this would never actually be used within this bundle?

```yaml
liip_functional_test:
    authentication:
        username: "a valid username"
        password: "the password of that user"
```

**Comment by lsmith77** [comment] 2015-07-11 06:09
indeed we are missing documentation on this .. would be good if you could add some, since I cannot find a good example quickly.

the work flow is essentially:

```
public function testSomeThing()
{
    ...
    // set a user to be used in the makeClient call 
    $this->loginAs($user);
    $client->makeClient(...);
    ..
}
```

see also https://github.com/liip/LiipFunctionalTestBundle/issues/161 and https://gist.github.com/beberlei/1223886

**Comment by phillipsnick** [comment] 2015-07-12 16:12
I made a little progress with this but still seems a little hit and miss.

When I get back round to this section of my app I'll see about writing up some docs and making a pull request :)

**Comment by lsmith77** [comment] 2016-01-07 06:48
duplicate of https://github.com/liip/LiipFunctionalTestBundle/issues/88

**Closed by lsmith77** 2016-01-07 06:48 UTC
Labels: verified
